### ISSUE TITLE
firefox issue related to SSL on your site?

### ISSUE THREAD

**Issue by rbaty-barr** [jenil/icongram#1]
firefox version 55.0.3 64 bit... getting an ssl error on the image source. https://icongram.jgog.in/fontawesome/close.svg

![image](https://user-images.githubusercontent.com/8059765/30830840-08e4545a-a20b-11e7-97e0-2f41c11962a9.png)

**Comment by jenil** [comment]
I just check on Firefox 55 OSX and it worked fine. What OS are you on?
Also, I have found a sponsor, so I will get a SSL certificate and the project will be more reliable by EOW 🎉

**Comment by rbaty-barr** [comment]
i am on windows 10 surfacebook... chrome and IE look to be fine... don't you love browsers :|

**Comment by jenil** [comment]
❤️ for all browsers is coming soon! I'll debug the Windows issue.

**Comment by rbaty-barr** [comment]
55.0.2 & .3 (32 bit) looks to be okay...  hmmm

**Comment by jenil** [comment]
The project is now on a new domain (the old one still will keep working). Can you try https://icongr.am/ and see if the error still persists?
