### ISSUE TITLE
Suggestion: spriting the icons used

### ISSUE THREAD

**Issue by beeing** [jenil/icongram#4]
Fantastic idea you have there.

Will be cool if there's a CLI build tool to extract and replace the links like `https://icongr.am/material/google-maps.svg?size=100&color=689f18` to `sprite.svg#google-maps` and then to generate the sprite file for performance.

I've not figured out on the size and color though, perhaps need to move it to style instead.

Been looking for a solution to tree-shake on web fonts but perhaps this is way cooler.

**Comment by jenil** [comment]
Maybe I didn't completely understand what you mean, but can you explain how would this be different from the sprite that comes with the icon library?

**Comment by beeing** [comment]
Well, my experience was not all icon libraries have everything that we need and to download and include the entire package just for few icons is kind of heavy.

So, this is like a bundler which only build the sprites based on what the programmer uses in the app.

Hope this helps 😄
